pipeline:
  name: chained-pipeline
  identifier: chianedpipeline
  projectIdentifier: ayushlab
  orgIdentifier: ayushtestorg
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Ayush
        repoName: simple_python_app
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8stestconnector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerk8stest
                    image: library/nginx
                    shell: Bash
                    command: pwd
    - stage:
        name: approve-deploy
        identifier: approvedeploy
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approve-deploy
                  identifier: approvedeploy
                  type: HarnessApproval
                  timeout: 2m
                  spec:
                    approvalMessage: Please approve to deploy this build to aws
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: chained-deploy
        identifier: chaineddeploy
        description: ""
        type: Pipeline
        spec:
          org: ayushtestorg
          project: ayushlab
          pipeline: awspipeline
          inputs:
            identifier: awspipeline
            stages:
              - stage:
                  identifier: aws
                  type: Deployment
                  spec:
                    service:
                      serviceInputs:
                        serviceDefinition:
                          type: ECS
                          spec:
                            artifacts:
                              primary:
                                primaryArtifactRef: <+input>
                                sources: <+input>
          outputs: []
