pipeline:
  name: repro-template
  identifier: reprotemplate
  projectIdentifier: bootcampciayush
  orgIdentifier: ayushtestorg
  tags: {}
  stages:
    - stage:
        name: template
        identifier: template
        tags: {}
        template:
          templateRef: account.remoteaccstagetemplate
          versionLabel: v1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - insert:
                      identifier: yugyj
                      steps:
                        - stepGroup:
                            name: test-step-group
                            identifier: teststepgroup
                            template:
                              templateRef: teststepgroup
                              versionLabel: v3
